logging:
  level:
    #        tk.mybatis: DEBUG
    com.yanping.manydb.manydb: DEBUG

server:
  port: 9956
  undertow:
    max-http-post-size: 0
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:

    base:
      #        jdbc-url: jdbc:mysql://192.168.216.22:3306/lark_admin?useUnicode=true&characterEncoding=UTF8&useSSL=true
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=true
      username: root
      password: root123
      #        password: 1PV%1i4*bdGQu&!i*mG22
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


# 配置swagger
swagger:
  max-page-size: 10000 #接口分页每页最大数量
  min-page-size: 10 #接口分页每页最小数量
  base-package: com.mht.lark.dsp
  title: lark-dsp
  version: 1.0.0.SNAPSHOT
  description: 数据共享服务
  contact:
    name: admin

